@Library('jenkins-pipelines-configuration')

CITemplate(
    serviceName: 'payments-service',
    language: 'angular',
    
    // Configuración Docker
    dockerRegistry: 'gcr.io/my-project',
    dockerPush: true,
    
    // Configuración CD
    deployK8s: true,
    namespace: 'production',
    
    // Configuración de Aprobación
    requireApproval: true,
    approver: 'admin-user,devops-group' // Usuarios o grupos permitidos para aprobar
)
