@Library('jenkins-pipelines-example') _

jenkinsPipelinesExample([
    language: 'Angular',    
    dockerRegistry: 'docker.io/mycompany',        
    approvers: 'admin',    
    typeDeployd: "helm", // helm & kubectl
    configRepoUrl: "" // Repository URL
    namespace: "" // namespace
    credentialID: {
    k8s-token: k8s_token_ci
    } // credentials of k8s - 
])