@Library('jenkins-pipelines-example') _

jenkinsPipelinesExample([
    language: 'Angular',    
    dockerRegistry: 'docker.io/mycompany',        
    approvers: 'admin',    
    typeDeployd: "helm", // helm & kubectl
    configRepoUrl: "" // Repository URL
])