FROM docker.io/angel5572/angular-chrome-test:v2 AS build
WORKDIR /app

# Instalar dependencias con lockfile si existe
COPY package*.json ./
COPY package-lock.json ./
RUN npm set registry https://registry.npmmirror.com/
RUN npm set fetch-timeout 300000 && npm set fetch-retries 10 && npm ci

COPY angular.json ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./
COPY tsconfig.spec.json ./
COPY karma.conf.js ./